spring.application.name=taskmanager

spring.datasource.url=jdbc:h2:mem:taskdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spirng.datasource.password=

spring.jap.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
